DROP TABLE IF EXISTS BOOKS;

CREATE TABLE BOOKS (
    ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(100),
    AUTHOR VARCHAR(100),
    GENRE VARCHAR(100),
    PRICE DECIMAL(5,2)
);

INSERT INTO BOOKS (TITLE, AUTHOR, GENRE, PRICE) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 'Fiction', 7.95);
INSERT INTO BOOKS (TITLE, AUTHOR, GENRE, PRICE) VALUES ('To Kill a Mockingbird', 'Harper Lee', 'Fiction', 6.95);
INSERT INTO BOOKS (TITLE, AUTHOR, GENRE, PRICE) VALUES ('1984', 'George Orwell', 'Fiction', 6.95);

SELECT * FROM BOOKS;